name: 🛠️ 构建 test

on:
  workflow_dispatch:

env:
  KERNEL_WORKSPACE: ${{ github.workspace }}/kernel_workspace
  release: "true"  # 默认设置为 true，表示需要发布
  REPOS_JSON: "repos.oneplus_11.json"  # 动态指定的 JSON 文件路径

jobs:
  parse-config:
    name: "📖 解析配置文件"
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.parse.outputs.repo }}
    steps:
      - name: "📚 检出代码"
        uses: actions/checkout@v3

      - name: "📝 解析指定的 JSON 文件"
        id: parse
        run: |
          echo "repo<<EOF" >> $GITHUB_OUTPUT
          jq '.[]' ${{ env.REPOS_JSON }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: "🛠️ 构建 KernelSU Next SUSFS"
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      - name: "🛠️ 模拟生成构建产物"
        run: |
          mkdir -p $KERNEL_WORKSPACE/AnyKernel3
          echo "This is a test file" > $KERNEL_WORKSPACE/AnyKernel3/testfile.txt

      - name: "📤 上传构建产物"
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_KernelSU_Next_${{ github.run_number }}_test
          path: "./AnyKernel3/*"

      - name: "🧧 创建 GitHub Release"
        uses: softprops/action-gh-release@v2
        if: ${{ env.release == 'true' }}
        with:
          tag_name: "KernelSU-Next-SUSFS-Test-${{ github.run_number }}"
          name: "KernelSU Next SUSFS 内核测试 v${{ github.run_number }}"
          generate_release_notes: true
          files: "${{ env.KERNEL_WORKSPACE }}/AnyKernel3_KernelSU_Next_${{ github.run_number }}_test.zip"