name: 🛠️ 构建 test

on:
  workflow_dispatch:

env:
  KERNEL_WORKSPACE: ${{ github.workspace }}/kernel_workspace
  release: "true"  # 默认设置为 true，表示需要发布
  REPOS_JSON: "repos.oneplus_11.json"  # 动态指定的 JSON 文件路径

jobs:
  parse-config:
    name: "📖 解析配置文件"
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.parse.outputs.repo }}
    steps:
      - name: "📚 检出代码"
        uses: actions/checkout@v3

      - name: "📝 解析指定的 JSON 文件"
        id: parse
        run: |
          echo "repo<<EOF" >> $GITHUB_OUTPUT
          jq '.[]' ${{ env.REPOS_JSON }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: "🛠️ 构建 KernelSU Next SUSFS"
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      - name: "🛠️ 模拟生成构建产物"
        run: |
          mkdir -p $KERNEL_WORKSPACE && cd $KERNEL_WORKSPACE
          cd $KERNEL_WORKSPACE
          echo "This is a test file" > ./testfile.txt

      - name: "🛠️ 创建 AnyKernel3"
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cp $KERNEL_WORKSPACE/testfile.txt ./AnyKernel3/

      - name: "📤 打包"
        id: package
        env:
          zipname: "AnyKernel3_KernelSU_Next_${{ github.run_number }}_test"
        run: |
          cd AnyKernel3/
          zip -q -r "${{ env.zipname }}.zip" *

      - name: "📤 上传构建产物"
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_KernelSU_Next_${{ github.run_number }}_test
          path: "./AnyKernel3/*"

      - name: "🔍 检查 AnyKernel3 目录内容"
        run: |
          ls -la $KERNEL_WORKSPACE/
          ls -la ${{ github.workspace }}/
          ls -la ${{ github.workspace }}/AnyKernel3/
      # - name: "🧧 创建 GitHub Release"
      #   uses: softprops/action-gh-release@v2
      #   if: ${{ env.release == 'true' }}
      #   with:
      #     tag_name: "KernelSU-Next-SUSFS-Test-${{ github.run_number }}"
      #     name: "KernelSU Next SUSFS 内核测试 v${{ github.run_number }}"
      #     generate_release_notes: true
      #     files: "${{ github.workspace }}/AnyKernel3_KernelSU_Next_${{ github.run_number }}_test.zip"