name: 🛠️ 测试参数读取

on:
  workflow_dispatch:

env:
  KERNEL_WORKSPACE: ${{ github.workspace }}/kernel_workspace
  release: "true"  # 默认设置为 true，表示需要发布
  REPOS_JSON: "repos.oneplus_11.json"  # 动态指定的 JSON 文件路径

jobs:
  parse-config:
    name: "📖 解析配置文件"
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.parse.outputs.repo }}
    steps:
      - name: "📚 检出代码"
        uses: actions/checkout@v3

      - name: "📝 解析指定的 JSON 文件"
        id: parse
        run: |
          echo "repo<<EOF" >> $GITHUB_OUTPUT
          jq -s '[.[][]]' ${{ env.REPOS_JSON }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build-kernel:
    name: "🛠️ 构建 KernelSU Next SUSFS"
    runs-on: ubuntu-latest
    needs: parse-config
    steps:
      - name: "🔄 测试参数读取1"
        env:
          CPU: ${{ fromJSON(needs.parse-config.outputs.repo)[0].CPU }}
          FEIL: ${{ fromJSON(needs.parse-config.outputs.repo)[0].FEIL }}
          ANDROID_VERSION: ${{ fromJSON(needs.parse-config.outputs.repo)[0].ANDROID_VERSION }}
          KERNEL_VERSION: ${{ fromJSON(needs.parse-config.outputs.repo)[0].KERNEL_VERSION }}
          CPUD: ${{ fromJSON(needs.parse-config.outputs.repo)[0].CPUD }}
        run: |
          echo "CPU: ${CPU}"
          echo "FEIL: ${FEIL}"
          echo "CPUD: ${CPUD}"
          echo "ANDROID_VERSION: ${ANDROID_VERSION}"
          echo "KERNEL_VERSION: ${KERNEL_VERSION}"

